server:
  port: 3000
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: clothing-mall
# mysql数据库
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/clothing-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password: root # Redis服务器连接密码（默认为空）
    timeout: 3000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  # 邮箱
  mail:
    username: 18762084218@163.com
    password: WBMRWMBAYPGIKRAU
    host: smtp.163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# mybatis plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0


